CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Department" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "City" text NOT NULL,
    "Street" text NOT NULL,
    "Home" text NOT NULL,
    "ZipCode" text NOT NULL,
    CONSTRAINT "PK_Department" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "MidleName" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "BirthDay" date NOT NULL,
    "Balance" bigint NOT NULL,
    "DepartmentId" integer,
    "UserRole" integer NOT NULL,
    "CreatedTime" timestamp with time zone NOT NULL,
    "UserName" text,
    "NormalizedUserName" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Department_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Department" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_Users_DepartmentId" ON "Users" ("DepartmentId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250719153446_Init', '8.0.18');

COMMIT;

